# Site settings
title: Aaron Blog
SEOTitle: 似同的博客 | Aaron Blog
header-img: img/home-bg.jpg
email: amoschen100@gmail.com
description: "持续好奇，学无边界。/； | Aaron 似同，，Product Manager，Data Scientist | 这里是 @Aaron 似同 的个人博客，共同发现宇宙真理。"
keyword: "似同, Aaron 似同, Aaron, 冼然, @李似同, Aaron Chen的博客, Aaron Blog, 博客, 科技, 互联网, 产品, 数据科学, 深度学习, 行业研究"
url: "https://dr-aaron.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     李似同
zhihu_username:     李似同
github_username:    Dr-Aaron
twitter_username:   李似同
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]
gems: [jekyll-paginate]

# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-seo-tag


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: dr-aaron

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
#  ba_track_id: [4271ed6948812672fbe5960361bfd25e]



# Google Analytics
ga_track_id: 'UA-221035997-1'            # Format: UA-xxxxxx-xx
ga_domain: https://dr-aaron.github.io/



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Grateful experimentalism<br>感恩着的体验派"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
    #     title: "乱序",
    #     href: "http://mida.re/"
    }
]
